import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Script from "next/script";

// import SplashCursor from "../../Reactbits/SplashCursor/SplashCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body cz-shortcut-listen="true">
        <Navbar />
        <Script
          type="module"
          src="https://unpkg.com/@splinetool/viewer@1.10.32/build/spline-viewer.js"
          strategy="beforeInteractive"
        />
        {/* <SplashCursor /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
